name: ci-deploy 
on:
  workflow_dispatch:
    # For easily adding a new tag and deploying
    inputs:
      version:
        description: 'New tag to add and deploy'
        required: true
permissions:
  contents: write
jobs:
  add-version:
    runs-on: ubuntu-latest
    name: Add version tag
    if: ${{ github.event_name == 'workflow_dispatch' }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure git
      run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

    - name: Add release tag
      # Force is used to replace any existing tag for the same version
      run: git tag -f ${{ github.event.inputs.version }}

    - name: Push tag
      run: git push -f origin ${{ github.event.inputs.version }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt      
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git fetch origin gh-pages --depth=1
      - run: mike deploy --push --no-redirect --update-aliases ${{ github.event.inputs.version }} latest
